/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/instruments/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Instruments */
        get: operations["search_instruments_api_v1_instruments_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/instruments/{instrument_id}/prices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Instrument Prices */
        get: operations["get_instrument_prices_api_v1_instruments__instrument_id__prices_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/baskets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Basket */
        post: operations["create_basket_api_v1_baskets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/baskets/{basket_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Basket */
        get: operations["get_basket_api_v1_baskets__basket_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/performance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analytics Performance */
        post: operations["analytics_performance_api_v1_analytics_performance_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/weights": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analytics Weights */
        post: operations["analytics_weights_api_v1_analytics_weights_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/risk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analytics Risk */
        post: operations["analytics_risk_api_v1_analytics_risk_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/correlation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analytics Correlation */
        post: operations["analytics_correlation_api_v1_analytics_correlation_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BasketConfigRequest */
        BasketConfigRequest: {
            /**
             * Basket Id
             * Format: uuid
             */
            basket_id: string;
            /**
             * Weight Method
             * @enum {string}
             */
            weight_method: "equal" | "inverse_vol" | "inverse_corr" | "risk_parity" | "beta_adjusted" | "market_cap" | "manual";
            /**
             * Gross Exposure
             * @default 1
             */
            gross_exposure: number;
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /**
             * End Date
             * Format: date
             */
            end_date: string;
            /** Benchmark Id */
            benchmark_id?: string | null;
            /**
             * Lookback Days
             * @default 90
             */
            lookback_days: number;
            /**
             * Include Funding Adj
             * @default true
             */
            include_funding_adj: boolean;
            /**
             * Include Trading Costs
             * @default true
             */
            include_trading_costs: boolean;
            /**
             * Fee Bps
             * @default 4
             */
            fee_bps: number;
            /**
             * Slippage Bps
             * @default 6
             */
            slippage_bps: number;
            /**
             * Rebalance Freq
             * @default none
             * @enum {string}
             */
            rebalance_freq: "none" | "daily" | "weekly" | "monthly";
        };
        /** BasketCreateRequest */
        BasketCreateRequest: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Benchmark Id */
            benchmark_id?: string | null;
            /** Legs */
            legs: components["schemas"]["BasketLegCreate"][];
        };
        /** BasketLegCreate */
        BasketLegCreate: {
            /**
             * Instrument Id
             * Format: uuid
             */
            instrument_id: string;
            /**
             * Side
             * @enum {string}
             */
            side: "long" | "short";
            /** Weight Override */
            weight_override?: number | string | null;
        };
        /** BasketLegResponse */
        BasketLegResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Side
             * @enum {string}
             */
            side: "long" | "short";
            /** Weight Override */
            weight_override: string | null;
            instrument: components["schemas"]["InstrumentResponse"];
        };
        /** BasketResponse */
        BasketResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            /** Benchmark Id */
            benchmark_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Legs */
            legs: components["schemas"]["BasketLegResponse"][];
        };
        /** CorrelationResponse */
        CorrelationResponse: {
            /** Symbols */
            symbols: string[];
            /** Matrix */
            matrix: number[][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InstrumentResponse */
        InstrumentResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Symbol */
            symbol: string;
            /** Name */
            name: string | null;
            /** Asset Class */
            asset_class: string;
            /** Exchange */
            exchange: string | null;
            /** Currency */
            currency: string;
        };
        /** PerformancePoint */
        PerformancePoint: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Basket Return */
            basket_return: number;
            /** Benchmark Return */
            benchmark_return: number;
            /** Drawdown */
            drawdown: number;
        };
        /** PerformanceResponse */
        PerformanceResponse: {
            /** Series */
            series: components["schemas"]["PerformancePoint"][];
            metrics: components["schemas"]["RiskMetrics"];
            /** Weights */
            weights: components["schemas"]["WeightSnapshot"][];
        };
        /** PriceDailyResponse */
        PriceDailyResponse: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Px Open */
            px_open: string | null;
            /** Px High */
            px_high: string | null;
            /** Px Low */
            px_low: string | null;
            /** Px Close */
            px_close: string;
            /** Px Adj Close */
            px_adj_close: string | null;
            /** Volume */
            volume: number | null;
        };
        /** RiskMetrics */
        RiskMetrics: {
            /** Annvol */
            annVol: number;
            /** Sharpe */
            sharpe: number;
            /** Maxdrawdown */
            maxDrawdown: number;
            /** Calmar */
            calmar: number;
            /** Sortino */
            sortino: number;
            /** Beta */
            beta: number;
            /** Netexposure */
            netExposure: number;
            /** Grossexposure */
            grossExposure: number;
            /** Fundingdrag */
            fundingDrag: number;
            /** Totalreturn */
            totalReturn: number;
            /** Vsbenchmark */
            vsbenchmark: number;
        };
        /** RiskResponse */
        RiskResponse: {
            metrics: components["schemas"]["RiskMetrics"];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WeightSnapshot */
        WeightSnapshot: {
            /**
             * Method
             * @enum {string}
             */
            method: "equal" | "inverse_vol" | "inverse_corr" | "risk_parity" | "beta_adjusted" | "market_cap" | "manual";
            /** Weights */
            weights: {
                [key: string]: number;
            };
        };
        /** WeightsResponse */
        WeightsResponse: {
            /** Weights */
            weights: components["schemas"]["WeightSnapshot"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    search_instruments_api_v1_instruments_search_get: {
        parameters: {
            query: {
                q: string;
                asset_class?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstrumentResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_instrument_prices_api_v1_instruments__instrument_id__prices_get: {
        parameters: {
            query: {
                from: string;
                to: string;
            };
            header?: never;
            path: {
                instrument_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PriceDailyResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_basket_api_v1_baskets_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BasketCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BasketResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_basket_api_v1_baskets__basket_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                basket_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BasketResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analytics_performance_api_v1_analytics_performance_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BasketConfigRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PerformanceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analytics_weights_api_v1_analytics_weights_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BasketConfigRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeightsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analytics_risk_api_v1_analytics_risk_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BasketConfigRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RiskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analytics_correlation_api_v1_analytics_correlation_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BasketConfigRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CorrelationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
